import { Component } from '@angular/core';
import { IReview } from '../review';

@Component({
  selector: 'app-reviews',
  templateUrl: './product-review.component.html',
  styleUrl: 'product-review.styles.css',

})
export class ReviewComponent {
  pageTitle = 'Product Reviews';
  currentProduct: number = 0;
  imageWidth: number = 400;
  imageHeight: number = 300;
  imageMargin: number = 0;
  showReview: boolean = false;
  reviews: IReview[] = [
    {
        "productName": "HiFiMan Edition XS",
        "review": "The HiFiMan Edition XS headphones are a remarkable addition to the world of audiophile-grade headphones, boasting an impressive blend of exceptional sound quality, comfort, and durability. From their robust build to their refined audio performance, these headphones cater to discerning listeners seeking an immersive and detailed sound experience.\n\nCrafted with meticulous attention to detail, the Edition XS showcases a sturdy construction using premium materials. The combination of metal and leather not only gives these headphones an elegant aesthetic but also contributes to their durability. The adjustable headband ensures a comfortable fit for extended listening sessions, while the plush earpads provide excellent isolation, allowing users to delve into their music without external disturbances.\n\nSonically, the Edition XS delivers a rich and dynamic sound signature that audiophiles crave. The headphones boast a wide soundstage, allowing for precise instrument separation and an immersive listening experience. The drivers produce crisp highs, well-defined mids, and punchy bass, maintaining clarity across various genres. Whether you're enjoying the intricate details of classical music or the thumping beats of electronic tracks, these headphones excel in reproducing audio with stunning accuracy.\n\nFurthermore, the Edition XS comes equipped with detachable cables, offering convenience and versatility. The inclusion of both balanced and unbalanced cables caters to different audio setups, allowing users to optimize their listening experience based on their preferences. While these headphones may come with a premium price tag, the exceptional build quality, outstanding sound performance, and versatility make them a worthwhile investment for serious audio enthusiasts seeking top-tier headphones.",
        "id": 0,
        "imageUrl": "assets/images/EditionXS.jpg",
    },
    {
        "productName": "Westone Mach 60",
        "review": "The Westone Mach 60 is a high-end, in-ear monitor (IEM) that promises exceptional audio quality and comfort for professionals and audiophiles alike. Crafted with precision and engineered for top-notch sound reproduction, these IEMs come packed with features that cater to discerning users looking for unparalleled audio fidelity.\n\nOne of the standout features of the Mach 60 is its six-driver balanced armature configuration. This setup delivers an impressive range of frequencies, ensuring a well-balanced sound signature with rich lows, detailed mids, and sparkling highs. The drivers are finely tuned to provide clarity across the spectrum, making them ideal for critical listening, studio monitoring, or immersive music enjoyment.\n\nComfort is a top priority with the Mach 60. The ergonomic design and lightweight construction contribute to a snug and secure fit, allowing for extended listening sessions without discomfort. Moreover, the package includes various ear tips and customization options, ensuring a personalized fit that effectively isolates external noise, enhancing the overall listening experience. The detachable MMCX cable adds convenience and durability, allowing for easy replacement or customization as per the user's preferences.\n\nIn terms of build quality, the Westone Mach 60 showcases excellent craftsmanship. The robust construction ensures durability, making these IEMs suitable for on-the-go use or stage performances. While the price point may be a bit steep for casual users, the Mach 60's performance and quality justify the investment for audiophiles, musicians, and sound professionals seeking top-tier audio accuracy and comfort in an in-ear monitor.",
        "id": 1,
        "imageUrl": "assets/images/Westone Mach 60.jpg",
    },
    {
        "productName": "Sennheiser HD 6XX",
        "review" : "The Sennheiser HD 6XX has solidified its place as a revered staple in the realm of audiophile headphones, delivering a listening experience that captivates enthusiasts and professionals alike. Born from the collaboration between Massdrop and Sennheiser, this model inherits the DNA of the iconic HD 650 while incorporating some subtle but impactful improvements.\n\nCrafted with meticulous attention to detail, the HD 6XX showcases an open-back design that contributes to its airy soundstage, offering an immersive audio journey. The velour-covered ear cups and well-padded headband ensure prolonged comfort during extended listening sessions, a testament to Sennheiser's commitment to both sonic excellence and user comfort.\n\nSonically, the HD 6XX embodies a balanced and natural sound signature. The renowned Sennheiser drivers deliver a rich, detailed sound with an emphasis on midrange clarity that's both articulate and nuanced. Its bass response is tight and controlled, offering depth without overpowering other frequencies, catering to those who prefer accuracy over exaggerated lows.\n\nOne standout feature of the HD 6XX is its versatility. Whether used for critical listening, studio monitoring, or casual enjoyment, these headphones excel across genres, faithfully reproducing intricate details in classical pieces while delivering the punch and energy demanded by modern tracks. The impedance of 300 ohms necessitates a capable amplifier to truly unlock its potential, ensuring an optimal listening experience.\n\nWhile the HD 6XX maintains a predominantly classic design, some users might desire additional features like detachable cables or in-line controls, which are not included in this model. However, these omissions hardly detract from the sheer sonic brilliance and comfort these headphones offer, making the Sennheiser HD 6XX an exceptional choice for audiophiles seeking a premium listening experience at an attainable price point.",
        "id": 2,
        "imageUrl": "assets/images/sennheiser-6xx-massdrop-slickdeals-review-1.jpg",
    },
    {
        "productName": "Tin Audio T2",
        "review": "The Tin Audio T2 earphones have generated significant buzz in the audio community for their exceptional sound quality at an affordable price point. These in-ear monitors boast a balanced armature driver setup, delivering a remarkable audio experience that punches well above its weight. The T2s are revered for their clarity, detail retrieval, and precise sound signature, making them an appealing choice for audiophiles and casual listeners alike.\n\nOne standout feature of the Tin Audio T2 is its neutral sound profile, which offers a balanced representation across the frequency spectrum. The mids are articulate and well-defined, presenting vocals and instruments with impressive clarity and accuracy. The highs are crisp and detailed without being harsh, contributing to an immersive listening experience that reveals nuances in your favorite tracks.\n\nMoreover, the build quality of the Tin Audio T2 is commendable. The earpieces are constructed from sturdy metal housings that exude durability, ensuring longevity even with regular use. Additionally, the detachable MMCX connectors add convenience and versatility, allowing for cable upgrades or replacements, which can further enhance the overall listening experience.\n\nIn conclusion, the Tin Audio T2 earphones stand out as an excellent choice for those seeking exceptional sound quality without breaking the bank. With its neutral and detailed sound signature, durable build, and upgradeable cables, these earphones offer an impressive value proposition that competes favorably with higher-priced options in the market. Whether you're a discerning audiophile or a casual music enthusiast, the Tin Audio T2s are well worth considering for an immersive and enjoyable listening experience.",
        "id": 3,
        "imageUrl": "assets/images/tin-hifi-t2-and-t2-pro.jpg",
    },
    {
        "productName": "Campfire Audio Holocene",
        "review": "The Campfire Audio Holocene is a true testament to the brand's commitment to delivering audiophile-grade earphones that not only excel in sound quality but also boast a striking design. Right out of the box, the meticulous craftsmanship is evident, with the earpieces featuring a unique translucent shell that showcases the intricate inner workings. The attention to detail extends to the MMCX connectors, ensuring a secure and reliable connection for uninterrupted listening sessions.\n\nWhen it comes to sound performance, the Holocene truly shines. The combination of a single 10mm dynamic driver and Campfire Audio's signature Tuned Acoustic Expansion Chamber (T.A.E.C.) technology results in a sonic experience that is both immersive and detailed. The low frequencies are deep and impactful, providing a rich foundation for various genres. The midrange is clear and articulate, allowing vocals and instrumentals to shine, while the high frequencies exhibit a crispness that adds a layer of excitement to the overall sound signature.\n\nComfort is another area where the Holocene excels. The ergonomic design of the earpieces, combined with the selection of high-quality materials, ensures a snug fit that remains comfortable even during extended listening sessions. The included selection of ear tips caters to different preferences, allowing users to customize their fit for optimal isolation and comfort. Whether you're on a long flight or a daily commute, the Holocene remains a pleasure to wear.\n\nIn terms of build quality and durability, Campfire Audio once again delivers a product that stands the test of time. The premium materials used in the construction, such as the precision-machined aluminum shell, not only contribute to the earphones' aesthetics but also ensure longevity. The detachable cable adds a layer of convenience, and the included carrying case offers protection during transport. Overall, the Campfire Audio Holocene is a top-tier choice for audio enthusiasts who demand uncompromising sound quality, exquisite design, and enduring build craftsmanship.",
        "id": 4,
        "imageUrl": "assets/images/Campfire Audio Holocene.png",
    },
    {
        "productName": "Sennheiser MOMENTUM 4",
        "review" : "The Sennheiser MOMENTUM 4 Wireless headphones are a testament to the brand's commitment to impeccable sound quality and premium design. With a blend of cutting-edge technology and sophisticated aesthetics, these headphones cater to audiophiles and fashion-conscious users alike.\n\nOne of the standout features of the MOMENTUM 4 Wireless is the audio performance. Powered by Sennheiser's renowned audio engineering, these headphones deliver an immersive and balanced sound signature. The rich, detailed soundstage is complemented by deep bass and crisp highs, offering a listening experience that is both precise and vibrant across various music genres.\n\nComfort is another area where the MOMENTUM 4 excels. The ear cups, crafted from luxurious materials like genuine leather and soft padding, provide excellent comfort even during extended listening sessions. The design is not just about comfort but also aesthetics the sleek, minimalist look combined with durable build quality exudes sophistication.\n\nThe active noise cancellation (ANC) on these headphones is impressive, effectively minimizing ambient noise without compromising audio quality. The transparency mode allows users to stay aware of their surroundings without taking the headphones off, adding to the versatility of these premium cans.\n\nThe integration of smart features such as touch controls, voice assistant support, and auto-pause/play functionality elevates the overall user experience. Additionally, the robust battery life of up to 17 hours with ANC enabled ensures prolonged usage without frequent recharging.\n\nWhile the Sennheiser MOMENTUM 4 Wireless headphones come at a premium price point, they deliver an exceptional blend of superior sound quality, comfort, and style. For those seeking top-tier wireless headphones that prioritize audio fidelity and craftsmanship, the MOMENTUM 4 Wireless stands as an enticing choice.",
        "id": 5,
        "imageUrl": "assets/images/Sennheiser-Momentum-4-Wireless-side-view.jpg",
    },
    {
        "productName": "Meze Empyrean Elite",
        "review": "The Meze Empyrean Elite is a formidable addition to the realm of high-end headphones, delivering an exceptional auditory experience that's nothing short of breathtaking. Crafted with meticulous attention to detail, these headphones merge premium aesthetics with unparalleled performance, catering to the audiophile's discerning tastes.\n\nDesign-wise, the Empyrean Elite exudes sophistication. Its blend of lightweight materials such as carbon fiber and aluminum ensures durability without compromising on comfort. The ergonomic design and plush ear cushions envelop the ears, providing hours of fatigue-free listening. The attention to comfort extends to the headband, which distributes weight evenly, allowing for extended listening sessions without discomfort.\n\nSonically, the Empyrean Elite achieves a level of sonic excellence that elevates the listening experience to new heights. The hybrid array driver system, combining planar magnetic and dynamic drivers, delivers an incredibly detailed, well-balanced sound signature. From the deepest bass tones to the crispest highs, every nuance of the music is reproduced with remarkable precision, offering a truly immersive audio journey.\n\nFurthermore, the imaging and soundstage presented by the Empyrean Elite are nothing short of remarkable. The headphones excel in creating a spacious, three-dimensional soundstage that effortlessly places instruments and vocals with pinpoint accuracy. This spatial accuracy lends itself well to a wide array of genres, from classical orchestras to electronic beats, ensuring a captivating listening experience across diverse musical tastes. In conclusion, the Meze Empyrean Elite stands as a pinnacle of audio craftsmanship, combining top-tier design, comfort, and sonic performance into an audiophile's dream headphone.",
        "id": 6,
        "imageUrl": "assets/images/Meze-Audio-Empyrean-ELITE-17.jpg",
    },
    {
        "productName": "AirPods Pro 2",
        "review": "The AirPods Pro 2 is a stellar addition to Apple's renowned lineup of wireless earbuds, combining cutting-edge technology with a sleek design for an immersive audio experience. One of the standout features is the active noise cancellation (ANC), which has been significantly improved from its predecessor. The AirPods Pro 2 effectively eliminates background noise, providing users with a truly immersive listening experience whether they're in a bustling city or a noisy commute.\n\nApple has continued to prioritize comfort, and the AirPods Pro 2 is no exception. The ear tips are customizable, allowing users to find the perfect fit for their ears. The ergonomic design ensures a snug and secure fit, making them ideal for extended use without discomfort. Whether you're working out, commuting, or simply relaxing, these earbuds stay securely in place, enhancing the overall user experience.\n\nAudio quality remains a strong suit for the AirPods Pro 2. The adaptive EQ technology automatically adjusts the sound based on the shape of the user's ear, delivering a rich and well-balanced audio profile. The bass is deep and impactful, while the mids and highs are clear and detailed. Whether you're into heavy bass beats or crisp vocals, the AirPods Pro 2 delivers a versatile and satisfying audio performance.\n\nThe integration of spatial audio adds another layer to the immersive experience. This feature provides a surround sound-like experience, making users feel like they're in the center of the action. Whether you're watching movies, playing games, or listening to music, spatial audio enhances the overall entertainment value of the AirPods Pro 2. With seamless connectivity to Apple devices and an impressive battery life, these earbuds continue to set the standard for premium wireless audio. Overall, the AirPods Pro 2 is a worthy investment for those seeking top-notch sound quality, comfort, and cutting-edge features in a compact and stylish package.",
        "id": 7,
        "imageUrl": "assets/images/AirPods Pro 2.jpg",
    },
    {
        "productName": "Beyerdynamic DT 770 PRO",
        "review": "The Beyerdynamic DT 770 PRO headphones are a testament to premium audio quality and comfort. Designed for professional use but equally beloved by audiophiles, these closed-back headphones boast a sturdy construction and exceptional sound performance. With three impedance options (32, 80, and 250 ohms), users can choose the version that best suits their intended application, whether for studio monitoring, mixing, or casual listening.\n\nOne of the standout features of the DT 770 PRO is its impeccable sound reproduction. The headphones offer a well-balanced sound profile with rich, detailed lows, clear and vibrant mids, and sparkling highs. The closed-back design effectively isolates external noise, allowing users to delve into their music without distraction. The soundstage is impressively wide for closed-back headphones, contributing to an immersive listening experience across various genres, from classical to electronic.\n\nComfort is another area where the DT 770 PRO shines. The plush velour earpads and adjustable headband ensure extended listening sessions remain fatigue-free. The circumaural design envelops the ears without applying excessive pressure, and the headphones' robust build quality inspires confidence in their durability. However, the size of the headphones and the slightly bulky design might not be everyone's cup of tea for portable use, as they are more suited for stationary setups.\n\nFor professionals seeking accuracy in their audio work, the Beyerdynamic DT 770 PRO headphones deliver in spades. Their precise sound reproduction, durable build, and comfort make them a top choice for mixing and monitoring tasks. Additionally, for audiophiles searching for high-quality sound and exceptional comfort in their listening experience, these headphones offer a compelling option that remains competitive even among newer models in the market.",
        "id": 8,
        "imageUrl": "assets/images/Beyerdynamic DT 770 PRO.jpg",
    }
    
    ];

    selectReview(id: number): void {
        console.log(id);
        this.currentProduct = id;
        this.showReview = true;
    }

    close(): void{
        this.showReview = false;
        console.log(this.showReview);
      }
}

