import { Component } from '@angular/core';
import { IReview } from '../../review';

@Component({
  selector: 'app-headphones',
  templateUrl: './headphones.component.html',
  styleUrl: './headphones.component.css',
})
export class HeadphonesComponent {
  pageTitle = 'Headphone Reviews';
  currentProduct: number = 0;
  imageWidth: number = 400;
  imageHeight: number = 300;
  imageMargin: number = 0;
  showReview: boolean = false;
  reviews: IReview[] = [
    {
        "productName": "Sennheiser HD 800 S",
        "review": "The Sennheiser HD 800 S stands as a pinnacle in the world of high-end headphones, offering an exceptional listening experience coveted by audiophiles and music enthusiasts alike. Renowned for its unparalleled sound quality and engineering prowess, these open-back headphones redefine what it means to immerse oneself in music.\n\nCrafted with precision and finesse, the HD 800 S boasts an innovative design that elevates comfort without compromising on performance. Its unique open-back architecture delivers a remarkably spacious soundstage, allowing every note, instrument, and nuance to breathe and resonate naturally. The use of cutting-edge materials like aerospace-grade metals and high-grade plastics contributes to its lightweight build, ensuring extended listening sessions remain comfortable.\n\nSound reproduction on the Sennheiser HD 800 S is nothing short of extraordinary. The headphones feature large 56mm dynamic drivers meticulously tuned to deliver an impeccably balanced sound signature. The result is an expansive audio presentation marked by crystal-clear highs, richly detailed mids, and tight, controlled bass. Audiophiles appreciate its accuracy and fidelity, capturing the nuances of recordings with astonishing realism.\n\nFurthermore, the HD 800 S embodies sophistication in its engineering, incorporating Sennheiser's patented absorber technology to minimize unwanted resonances, thus enhancing clarity and precision. The detachable cable with a durable connector adds to its practicality, allowing for customization and future upgrades. Though a substantial investment, the Sennheiser HD 800 S unquestionably stands as a benchmark for uncompromising audio quality, making it a top choice for those seeking the absolute best in headphone performance.",
        "id": 0,
        "imageUrl": "assets/images/Sennheiser HD 800 S.jpg",
    },
    {
        "productName": "HiFiMan Edition XS",
        "review": "The HiFiMan Edition XS headphones are a remarkable addition to the world of audiophile-grade headphones, boasting an impressive blend of exceptional sound quality, comfort, and durability. From their robust build to their refined audio performance, these headphones cater to discerning listeners seeking an immersive and detailed sound experience.\n\nCrafted with meticulous attention to detail, the Edition XS showcases a sturdy construction using premium materials. The combination of metal and leather not only gives these headphones an elegant aesthetic but also contributes to their durability. The adjustable headband ensures a comfortable fit for extended listening sessions, while the plush earpads provide excellent isolation, allowing users to delve into their music without external disturbances.\n\nSonically, the Edition XS delivers a rich and dynamic sound signature that audiophiles crave. The headphones boast a wide soundstage, allowing for precise instrument separation and an immersive listening experience. The drivers produce crisp highs, well-defined mids, and punchy bass, maintaining clarity across various genres. Whether you're enjoying the intricate details of classical music or the thumping beats of electronic tracks, these headphones excel in reproducing audio with stunning accuracy.\n\nFurthermore, the Edition XS comes equipped with detachable cables, offering convenience and versatility. The inclusion of both balanced and unbalanced cables caters to different audio setups, allowing users to optimize their listening experience based on their preferences. While these headphones may come with a premium price tag, the exceptional build quality, outstanding sound performance, and versatility make them a worthwhile investment for serious audio enthusiasts seeking top-tier headphones.",
        "id": 1,
        "imageUrl": "assets/images/EditionXS.jpg",
    },
    {
        "productName": "Beyerdynamic DT 770 PRO",
        "review": "The Beyerdynamic DT 770 PRO headphones are a testament to premium audio quality and comfort. Designed for professional use but equally beloved by audiophiles, these closed-back headphones boast a sturdy construction and exceptional sound performance. With three impedance options (32, 80, and 250 ohms), users can choose the version that best suits their intended application, whether for studio monitoring, mixing, or casual listening.\n\nOne of the standout features of the DT 770 PRO is its impeccable sound reproduction. The headphones offer a well-balanced sound profile with rich, detailed lows, clear and vibrant mids, and sparkling highs. The closed-back design effectively isolates external noise, allowing users to delve into their music without distraction. The soundstage is impressively wide for closed-back headphones, contributing to an immersive listening experience across various genres, from classical to electronic.\n\nComfort is another area where the DT 770 PRO shines. The plush velour earpads and adjustable headband ensure extended listening sessions remain fatigue-free. The circumaural design envelops the ears without applying excessive pressure, and the headphones' robust build quality inspires confidence in their durability. However, the size of the headphones and the slightly bulky design might not be everyone's cup of tea for portable use, as they are more suited for stationary setups.\n\nFor professionals seeking accuracy in their audio work, the Beyerdynamic DT 770 PRO headphones deliver in spades. Their precise sound reproduction, durable build, and comfort make them a top choice for mixing and monitoring tasks. Additionally, for audiophiles searching for high-quality sound and exceptional comfort in their listening experience, these headphones offer a compelling option that remains competitive even among newer models in the market.",
        "id": 2,
        "imageUrl": "assets/images/Beyerdynamic DT 770 PRO.jpg",
    },
    {
        "productName": "Meze Empyrean Elite",
        "review": "The Meze Empyrean Elite is a formidable addition to the realm of high-end headphones, delivering an exceptional auditory experience that's nothing short of breathtaking. Crafted with meticulous attention to detail, these headphones merge premium aesthetics with unparalleled performance, catering to the audiophile's discerning tastes.\n\nDesign-wise, the Empyrean Elite exudes sophistication. Its blend of lightweight materials such as carbon fiber and aluminum ensures durability without compromising on comfort. The ergonomic design and plush ear cushions envelop the ears, providing hours of fatigue-free listening. The attention to comfort extends to the headband, which distributes weight evenly, allowing for extended listening sessions without discomfort.\n\nSonically, the Empyrean Elite achieves a level of sonic excellence that elevates the listening experience to new heights. The hybrid array driver system, combining planar magnetic and dynamic drivers, delivers an incredibly detailed, well-balanced sound signature. From the deepest bass tones to the crispest highs, every nuance of the music is reproduced with remarkable precision, offering a truly immersive audio journey.\n\nFurthermore, the imaging and soundstage presented by the Empyrean Elite are nothing short of remarkable. The headphones excel in creating a spacious, three-dimensional soundstage that effortlessly places instruments and vocals with pinpoint accuracy. This spatial accuracy lends itself well to a wide array of genres, from classical orchestras to electronic beats, ensuring a captivating listening experience across diverse musical tastes. In conclusion, the Meze Empyrean Elite stands as a pinnacle of audio craftsmanship, combining top-tier design, comfort, and sonic performance into an audiophile's dream headphone.",
        "id": 3,
        "imageUrl": "assets/images/Meze-Audio-Empyrean-ELITE-17.jpg",
    },
    {
        "productName": "Sennheiser HD 6XX",
        "review" : "The Sennheiser HD 6XX has solidified its place as a revered staple in the realm of audiophile headphones, delivering a listening experience that captivates enthusiasts and professionals alike. Born from the collaboration between Massdrop and Sennheiser, this model inherits the DNA of the iconic HD 650 while incorporating some subtle but impactful improvements.\n\nCrafted with meticulous attention to detail, the HD 6XX showcases an open-back design that contributes to its airy soundstage, offering an immersive audio journey. The velour-covered ear cups and well-padded headband ensure prolonged comfort during extended listening sessions, a testament to Sennheiser's commitment to both sonic excellence and user comfort.\n\nSonically, the HD 6XX embodies a balanced and natural sound signature. The renowned Sennheiser drivers deliver a rich, detailed sound with an emphasis on midrange clarity that's both articulate and nuanced. Its bass response is tight and controlled, offering depth without overpowering other frequencies, catering to those who prefer accuracy over exaggerated lows.\n\nOne standout feature of the HD 6XX is its versatility. Whether used for critical listening, studio monitoring, or casual enjoyment, these headphones excel across genres, faithfully reproducing intricate details in classical pieces while delivering the punch and energy demanded by modern tracks. The impedance of 300 ohms necessitates a capable amplifier to truly unlock its potential, ensuring an optimal listening experience.\n\nWhile the HD 6XX maintains a predominantly classic design, some users might desire additional features like detachable cables or in-line controls, which are not included in this model. However, these omissions hardly detract from the sheer sonic brilliance and comfort these headphones offer, making the Sennheiser HD 6XX an exceptional choice for audiophiles seeking a premium listening experience at an attainable price point.",
        "id": 4,
        "imageUrl": "assets/images/sennheiser-6xx-massdrop-slickdeals-review-1.jpg",
    },
    {
        "productName": "Audio-Technica ATH-M20x",
        "review": "The Audio-Technica ATH-M20x headphones are a fantastic entry-level option for those diving into the world of professional audio. With a sleek design and sturdy construction, these headphones offer exceptional durability without compromising comfort. The circumaural design and cushioned ear cups provide a snug fit, allowing for extended listening sessions without causing discomfort or fatigue.\n\nOne of the standout features of the ATH-M20x is its impressive audio quality. The headphones deliver a well-balanced sound profile, making them suitable for various applications, from casual music listening to studio monitoring. The 40mm drivers produce clear, accurate sound across the frequency spectrum, offering decent bass response without overpowering the mids and highs. This balance is particularly beneficial for mixing and recording tasks, allowing for precise audio evaluation.\n\nDurability is a key highlight of these headphones. Built with robust materials, the ATH-M20x can withstand frequent use and minor impacts, making them a reliable companion for daily use or on-the-go scenarios. The adjustable headband and ear cups swivel 90 degrees for convenient storage and portability, while the thick, single-sided cable minimizes tangles and adds to the overall durability.\n\nWhile the Audio-Technica ATH-M20x excels in many areas, it's essential to note that it lacks certain features found in higher-end models. For instance, these headphones do not come with a detachable cable or inline controls, which might be a downside for some users seeking more versatility or convenience. Additionally, the sound isolation, while decent, might not completely block out external noise in loud environments. However, considering its price point and performance, the ATH-M20x remains an outstanding choice for beginners and budget-conscious individuals looking for reliable, high-quality headphones.",
        "id": 5,
        "imageUrl": "assets/images/Audio-Technica ATH-M20x.jpg",
    },
    {
        "productName": "Focal Bathys",
        "review": "The Focal Bathys is a true testament to audio engineering excellence, delivering a sonic experience that transcends expectations. From the moment you lay eyes on these premium headphones, the sleek and sophisticated design immediately sets the stage for the auditory journey that awaits. Crafted with meticulous attention to detail, the Bathys boasts a luxurious blend of comfort and style, making it a standout choice for audiophiles with discerning taste.\n\nOne of the standout features of the Focal Bathys is its impeccable sound quality. The headphones deliver a rich, immersive audio experience that captures the nuances of every note and instrument with astonishing clarity. The precision-engineered drivers reproduce a wide frequency range, ensuring that you can hear the subtleties in your favorite tracks that might go unnoticed with lesser headphones. Whether you're a fan of classical compositions or bass-heavy beats, the Focal Bathys adapts effortlessly, offering a well-balanced sound profile that caters to a variety of musical preferences.\n\nComfort is a key consideration for any pair of headphones, and the Focal Bathys excels in this department. The over-ear design, coupled with plush ear cushions, provides a snug and comfortable fit for extended listening sessions. The adjustable headband ensures a customized fit, catering to users with varying head sizes. The premium materials used in the construction not only contribute to the headphones' durability but also add a touch of opulence to the overall design.\n\nIn terms of connectivity and convenience, the Focal Bathys doesn't disappoint. The headphones come equipped with the latest Bluetooth technology, allowing for a seamless wireless experience. The intuitive controls on the ear cups make it easy to adjust volume, skip tracks, and take calls with just a few simple gestures. Additionally, the impressive battery life ensures that the music keeps playing for an extended period, making the Focal Bathys a reliable companion for those on the go. In conclusion, the Focal Bathys redefines what is possible in the realm of premium headphones, offering an unrivaled combination of aesthetics, comfort, and audio performance.",
        "id": 6,
        "imageUrl": "assets/images/Bathys.jpg",
    },
    {
        "productName": "Philips Fidelio X3",
        "review": "The Philips Fidelio X3 headphones are a testament to the brand's commitment to delivering an unparalleled audio experience. Boasting a sleek and sophisticated design, these over-ear headphones immediately make a visual statement. The premium build quality is evident, with a combination of metal and luxurious materials that not only exude durability but also contribute to the overall comfort during extended listening sessions.\n\nWhen it comes to sound performance, the Fidelio X3 truly shines. The open-back design provides an expansive soundstage, allowing for an immersive audio experience that captures every nuance of your favorite music. The 50mm neodymium drivers deliver a rich and well-balanced sound signature, emphasizing both the lows and highs without sacrificing clarity. Whether you're a casual listener or an audiophile, the Fidelio X3 impresses with its ability to reproduce audio in a way that feels authentic and true to the original recording.\n\nComfort is a key factor for any pair of headphones, and the Fidelio X3 excels in this department. The plush ear cushions, crafted from memory foam, provide a snug fit without causing discomfort during prolonged use. The adjustable headband ensures a personalized and secure fit for a wide range of head sizes. Additionally, the breathable materials used in the ear cups contribute to a comfortable and enjoyable listening experience, making these headphones suitable for extended periods of use.\n\nIn terms of connectivity and convenience, the Fidelio X3 offers a detachable cable with a 3.5mm jack, providing compatibility with a variety of devices. The inclusion of a 6.3mm adapter further enhances its versatility, catering to audiophiles who prefer high-end audio equipment. The attention to detail in both design and performance makes the Philips Fidelio X3 a top-tier choice for those seeking a premium over-ear headphone experience, blending style, comfort, and exceptional sound quality seamlessly.",
        "id": 7,
        "imageUrl": "assets/images/Fidelio-X3-main.jpg",
   },
   {
        "productName": "Fiio FT3",
        "review": "The Fiio FT3 is a compact and feature-packed in-ear monitor that has garnered attention for its impressive audio performance and sleek design. As a budget-friendly option in Fiio's extensive lineup, the FT3 manages to deliver a well-balanced sound profile that caters to both audiophiles and casual listeners alike. The build quality of these earphones is commendable, featuring a durable aluminum housing that not only enhances durability but also contributes to a premium aesthetic.\n\nOne of the standout features of the FT3 is its versatility in providing a rich audio experience across various genres. The dual-driver setup ensures a dynamic range, with crisp highs, detailed mids, and punchy bass. The soundstage, though not expansive, is surprisingly immersive for in-ear monitors in this price range. Whether you're into rock, pop, or classical music, the FT3 manages to reproduce a balanced and enjoyable listening experience, making it a reliable companion for daily use.\n\nComfort is a key factor when it comes to in-ear monitors, and the FT3 doesn't disappoint. With a selection of silicone and foam ear tips included in the package, users can find the perfect fit for extended listening sessions without discomfort. The over-ear design of the cable provides a secure fit, ensuring that the earphones stay in place during physical activities, making them suitable for on-the-go use or workouts.\n\nIn terms of connectivity, the FT3 is equipped with a standard 3.5mm audio jack, making it compatible with a wide range of devices, from smartphones to digital audio players. The included detachable cable adds to the convenience, allowing users to replace it easily if needed. Overall, the Fiio FT3 stands out as an excellent choice for those seeking a budget-friendly, yet high-quality, in-ear monitor, offering a compelling combination of impressive audio performance, durable build, and user-friendly features.",
        "id": 8,
        "imageUrl": "assets/images/Fiio FT3.jpg",
   }
  ];

  selectReview(id: number): void {
    console.log(id);
    this.currentProduct = id;
    this.showReview = true;
  } 

  close(): void{
    this.showReview = false;
    console.log(this.showReview);
  }
}
